Fix Autoform Submit Problem
Meteor-Community-Packages/meteor-collection-hooks pull request #283
Opened 2022-08-22 15:18 UTC by cpravetz

Fixes problem with callbacks being lost because args passed from autoform include a validation object while collection-hooks assumes only two args.

2022-08-23 20:11 UTC, jankapunkt commented
@cpravetz thanks a lot this pull request. Can you please add a bit more info, for which AutoForm method or hook this fix is?

2022-08-24 12:45 UTC, cpravetz commented
Sorry - the patch addresses issue #1710 in the meteor-autoform repo. The callback passed during submit gets lost when collection-hooks expects two arguments and autoform passes three - so actions after the actual collection submit happens are never called.

2022-08-25 12:39 UTC, jankapunkt commented
Related: https://github.com/Meteor-Community-Packages/meteor-autoform/issues/1710

2022-08-25 12:45 UTC, jankapunkt requested changes
Just a minor fix then we can merge

2022-08-25 12:45 UTC, jankapunkt commented on insert.js
> +const async = typeof callback === 'function'
Please indent this line by two spaces.

2022-08-25 13:55 UTC, cpravetz commented on insert.js
> +const async = typeof callback === 'function'
Done.

2022-08-27 09:50 UTC, jankapunkt approved these changes

2022-08-27 09:51 UTC, jankapunkt commented
@cpravetz all good
@StorytellerCZ this can be merged and published. Can you do that?

2022-08-27 13:11 UTC, copleykj commented
@jankapunkt you should have the ability to do that if you wanted to.

2022-08-28 20:54 UTC, StorytellerCZ requested changes
Please add a changelog entry and then I will merge and publish a patch release.

2022-09-03 10:29 UTC, StorytellerCZ approved these changes

2022-09-03 10:30 UTC, merged

2022-09-03 11:01 UTC, StorytellerCZ commented
Published in matb33:collection-hooks@1.1.3