Added support for async collection methods
Meteor-Community-Packages/meteor-collection-hooks pull request #299
Opened 2023-08-28 08:58 UTC by jdgjsag67251

This PR adds support for Meteor's new async collection methods.

See #288.

2023-08-28 10:00 UTC, Jantje19 commented on collection-hooks.js
> +    Object.entries(advices).forEach(function ([method, advice]) {
I'm an idiot. I totally did this in the wrong place.

2023-08-28 10:01 UTC, jdgjsag67251 commented on collection-hooks.js
> +    Object.entries(advices).forEach(function ([method, advice]) {
I am an idiot. I totally did this in the wrong place.

2023-08-29 11:02 UTC, StorytellerCZ requested changes
Please use *Async methods when calling DB.
Once we merge this we should first move to support async functions in hooks and then move the hooks internals to use the new async functions to be ready for Meteor 3.

2023-08-29 11:02 UTC, StorytellerCZ commented on tests/async.js
> +    const id = collection.insert({ test: true })
Use `insertAsync` as above

2023-08-30 13:48 UTC, jdgjsag67251 commented
Cool, thnx. I've updated the PR

2023-08-30 15:30 UTC, StorytellerCZ approved these changes

2023-08-31 06:29 UTC, jankapunkt approved these changes

2023-08-31 06:30 UTC, jankapunkt commented
That's great @jdgjsag67251 :+1:  Thanks a lot!

2023-08-31 07:03 UTC, merged